.TH "Main.Beginner" 3 "Wed Mar 20 2024 11:46:46" "Type Tester" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.Beginner
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMain\&.Parrent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBMain\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Main\&.Beginner\&.__init__ ( self)"

.PP
Reimplemented from \fBMain\&.Parrent\fP\&.
.PP
Definition at line \fB39\fP of file \fBMain\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Type Tester from the source code\&.
