.TH "Main.Parrent" 3 "Wed Mar 20 2024 11:46:46" "Type Tester" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.Parrent
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMain\&.Beginner\fP, \fBMain\&.Expert\fP, and \fBMain\&.Intermidiate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBMain\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Main\&.Parrent\&.__init__ ( self)"

.PP
Reimplemented in \fBMain\&.Beginner\fP, \fBMain\&.Intermidiate\fP, and \fBMain\&.Expert\fP\&.
.PP
Definition at line \fB29\fP of file \fBMain\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Type Tester from the source code\&.
