.TH "md__r_e_a_d_m_e" 3 "Wed Mar 20 2024 11:46:46" "Type Tester" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Type Tester 
.PP
Tests your typing speed and accuracy
.SH "Getting Started"
.PP
Start the program, either login or sign up, You only need a username, and it will make a folder that saves every test you make
.SS "Installing"
Just unpack the zip file, and open the \fBMain\&.py\fP file
.SH "Usage"
.PP
After you have logged in, or signed in, you need to choose a difficulty, and from there you get a sentence you'll need to copy as fast as possible
.SH "Acknowledgments"
.PP
I'll aknowlegde my current teacher Kenneth Hebel, and my former teacher Talha Mahmood Sheikh for teaching me how to make a program like this\&. 
