.TH "phrases" 3 "Wed Mar 20 2024 11:46:46" "Type Tester" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phrases
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBTestPhrase\fP"
.br
.ti -1c
.RI "list \fBBeginnerPhrase\fP"
.br
.ti -1c
.RI "list \fBIntiermidiatePhrase\fP"
.br
.ti -1c
.RI "list \fBExpertPhrase\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list phrases\&.BeginnerPhrase"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "BegTest"
3 ]
.fi

.PP
Definition at line \fB5\fP of file \fBphrases\&.py\fP\&.
.SS "list phrases\&.ExpertPhrase"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "ExpTest"
3 ]
.fi

.PP
Definition at line \fB13\fP of file \fBphrases\&.py\fP\&.
.SS "list phrases\&.IntiermidiatePhrase"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "InterTest"
3 ]
.fi

.PP
Definition at line \fB9\fP of file \fBphrases\&.py\fP\&.
.SS "list phrases\&.TestPhrase"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "Jeg er en taberabe",
3 ]
.fi

.PP
Definition at line \fB1\fP of file \fBphrases\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Type Tester from the source code\&.
