.TH "phrases.py" 3 "Wed Mar 20 2024 11:54:22" "Type Tester" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phrases.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBphrases\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBphrases\&.TestPhrase\fP"
.br
.ti -1c
.RI "list \fBphrases\&.BeginnerPhrase\fP"
.br
.ti -1c
.RI "list \fBphrases\&.IntiermidiatePhrase\fP"
.br
.ti -1c
.RI "list \fBphrases\&.ExpertPhrase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Type Tester from the source code\&.
